name: usls
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - xarray
  - zarr
  - fsspec
  - gcsfs
  - matplotlib
  - requests
  - cdsapi
  - netcdf4
  - h5netcdf
  - h5py
  - dask
  - rasterio
  - rioxarray
  - pyproj
  - scikit-learn
  - pystac-client
  - nbstripout
  - pip:
    - pyprojroot
    - planetary-computer